checks:
  check_uptime:
    title: Uptime
    description: Controleer de uptime van de host
    command: "awk '{print int($1 / 86400)}' /proc/uptime"
    fail_when: ">"
    fail_value: ${uptime_limit}
    vars:
      uptime_limit: "77"
